
services:
  streamlit:
    build:
      dockerfile: build/streamlit/Dockerfile
      context: .
    container_name: streamlit
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      PAGE_SIZE: ${PAGE_SIZE}
      OPENAI_API_SERVICE: ${OPENAI_API_SERVICE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      RAPID_CLIENT_ID: ${RAPID_CLIENT_ID}
      RAPID_CLIENT_SECRET: ${RAPID_CLIENT_SECRET}
    ports: 
     - 8501:8501
    volumes:
      - ./src/streamlit:/app

  openai-apiserver:
    build:
      context: .
      dockerfile: dev_components/openai_apiserver/Dockerfile
    container_name: apiserver
    ports:
      - 8080:80
    volumes:
      - ./dev_components/openai_apiserver:/code/app

  directus:
    image: directus/directus:10.8.3
    container_name: directus
    ports:
      - 8055:8055
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_FILENAME: ${DB_FILENAME}

  directus-mapping-init:
    image: python:3.10
    container_name: directus-init
    environment:
      DIRECTUS_HOST: ${DIRECTUS_HOST}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./dev_components/directus/init.py:/init.py
    depends_on:
      - directus
    command: >
      bash -c '
        pip install requests
        python /init.py
      '

volumes:
  directus_database:
  directus_uploads:
