
services:
  streamlit:
    build:
      dockerfile: ./build/streamlit/Dockerfile
      context: .
    container_name: streamlit
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      PAGE_SIZE: ${PAGE_SIZE}
      OPENAI_API_SERVICE: ${OPENAI_API_SERVICE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      RAPID_CLIENT_ID: ${RAPID_CLIENT_ID}
      RAPID_CLIENT_SECRET: ${RAPID_CLIENT_SECRET}

    ports: 
     - 8501:8501
    volumes:
      - ./src/streamlit:/app

